<Project>
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <NoWarn>NU1701,CS0436</NoWarn>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>

        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <PropertyGroup>
        <PreserveDependenciesForRuntime Condition="'$(PreserveDependenciesForRuntime)' == ''">false</PreserveDependenciesForRuntime>
        <_Unity3DSdkExcludeAssets Condition="'$(PreserveDependenciesForRuntime)' == 'true' And '$(Configuration)' == 'Debug'"></_Unity3DSdkExcludeAssets>
        <_Unity3DSdkExcludeAssets Condition="'$(_Unity3DSdkExcludeAssets)' == '' And '$(PreserveDependenciesForRuntime)' != 'true'">runtime</_Unity3DSdkExcludeAssets>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Unity3D.SDK" PrivateAssets="all" Exclude="$(_Unity3DSdkExcludeAssets)"/>
        <PackageReference Include="JetBrains.Annotations" />
        <PackageReference Include="PolySharp">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
        <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" PrivateAssets="all" />
        <PackageReference Include="Microsoft.Bcl.HashCode" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup Condition="'$(UseRoslynPackages)' == 'true'">
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime;build;native;contentfiles;analyzers;buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" ExcludeAssets="runtime" PrivateAssets="all" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" ExcludeAssets="runtime" PrivateAssets="all" />
    </ItemGroup>
</Project>