using System;
using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Surject.Generators.Models.Primitives;
using Surject.Shared.Extensions;
using Surject.Shared.Helpers;
using GeneratedSource = (string name, Microsoft.CodeAnalysis.Text.SourceText sourceText);

namespace Surject.Generators.Emitters.Helpers;

internal static class EmitHelpers {
    internal static void EmitGeneratedFileHeader(IndentedTextWriter writer) {
        writer.WriteLine("// <auto-generated />");
        writer.WriteLine("//------------------------------------------------------------------------------");
        writer.WriteLine("// This code was automatically generated by Surject Generators.");
        writer.WriteLine("//");
        writer.WriteLine("// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.");
        writer.WriteLine("//------------------------------------------------------------------------------");
        writer.WriteLine();
        
        writer.WriteLine("#nullable enable");
        
        // Field declared but never used
        writer.WriteLine($"#pragma warning disable 169");
    }

    internal static void EmitGeneratedCodeAttribute(IndentedTextWriter writer) {
        writer.WriteLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"SurjectGenerator\", \"1.0.0\")]");
    }

    internal static void EmitExcludeFromCodeCoverageAttribute(IndentedTextWriter writer) {
        writer.WriteLine($"[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
    }

    internal static void EmitEditorBrowsableNeverAttribute(IndentedTextWriter writer) {
        writer.WriteLine($"[global::System.ComponentModel.EditorBrowsable(");
        writer.Indent++;
        writer.WriteLine($"global::System.ComponentModel.EditorBrowsableState.Never)]");
        writer.Indent--;
    }

    internal static void EmitDoesNotReturnAttribute(IndentedTextWriter writer) {
        writer.WriteLine($"[global::System.Diagnostics.CodeAnalysis.DoesNotReturn]");
    }

    internal static void EmitMethodImplAttribute(IndentedTextWriter writer, MethodImplOptions options) {
        writer.WriteLine("[global::System.Runtime.CompilerServices.MethodImpl(");
        writer.Indent++;
        writer.WriteLine($"global::System.Runtime.CompilerServices.MethodImplOptions.{options.ToString()})]");
        writer.Indent--;
    }

    internal static void EmitDefaultExecutionOrderAttribute<TEnum>(IndentedTextWriter writer, TEnum order) where TEnum : Enum {
        writer.WriteLine("[global::UnityEngine.DefaultExecutionOrder(");
        writer.Indent++;
        writer.WriteLine($"(int)global::{typeof(TEnum)}.{order.ToString()})]");
        writer.Indent--;
    }

    internal static GeneratedSource EmitFile(string? @namespace, string fileName, Action<IndentedTextWriter> emitBody) {
        using StringWriter sr = new();
        using IndentedTextWriter writer = new(sr);

        EmitGeneratedFileHeader(writer);
        writer.WriteLine();
        
        if (@namespace is not null) {
            writer.WriteLine($"namespace {@namespace} {{");
            writer.Indent++;
        }
        
        emitBody(writer);
        
        if (@namespace is not null) {
            writer.Indent--;
            writer.WriteLine("}");
        }

        SourceText text = SourceText.From(sr.ToString(), Encoding.UTF8);
        return (fileName, text);
    }
    
    internal static void EmitTypeDeclarationFromModel(
        TypeDeclModel decl,
        IndentedTextWriter writer,
        string[]? inheritance = null)
    {
        ITypeReferenceModel typeRef = decl.AsTypeRef;
        
        string accessibility = decl.AccessModifier.AsDeclString();
        string isPartial = decl.IsPartial ? "partial " : string.Empty;
        string isSealed = decl.IsSealed && typeRef.TypeKind is not TypeKind.Struct ? "sealed " : string.Empty;
        string isStatic = decl.IsStatic ? "static " : string.Empty;
        
        string typeKeyword = typeRef.TypeKind switch {
            TypeKind.Interface => "interface",
            TypeKind.Struct => typeRef.IsRecord ? "record struct" : "struct",
            TypeKind.Enum => "enum",
            TypeKind.Class => typeRef.IsRecord ? "record" : "class",
            _ => ThrowHelpers.ThrowUnhandledBranch<string>(typeRef.TypeKind)
        };
        
        string typeParams = typeRef.TypeParameters.Length > 0
            ? "<" + string.Join(", ", typeRef.TypeParameters.Select(static tp => tp.FQNGenericBased)) + ">"
            : string.Empty;
        
        string constraints = typeRef.Constraints.Length > 0
            ? string.Join(" ", typeRef.Constraints.Select(static ct => ct.ToString()))
            : string.Empty;

        string inheritFrom = inheritance is not null
            ? string.Join(", ", inheritance)
            : string.Empty;

        string output = $"{accessibility} {isPartial} {isSealed} {isStatic} {typeKeyword} " +
                        $"{decl.TypeNameNoArityNoFQN}{typeParams} " +
                        $"{(!string.IsNullOrEmpty(inheritFrom) ? $": {inheritFrom} " : "")}" +
                        $"{constraints} {{";
        
        writer.WriteLine(output.CollapseRedundantWhitespace());
    }
}