using System.CodeDom.Compiler;

namespace Surject.Generators.Emitters.Helpers;

internal static class SurjectHeaderEmitter {
    internal static void WriteGeneratedFileHeader(IndentedTextWriter writer) {
        writer.WriteLine("// <auto-generated />");
        writer.WriteLine("//------------------------------------------------------------------------------");
        writer.WriteLine("// This code was automatically generated by Surject Generators.");
        writer.WriteLine("//");
        writer.WriteLine("// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.");
        writer.WriteLine("//------------------------------------------------------------------------------");
        writer.WriteLine();
        
        // Field declared but never used
        writer.WriteLine($"#pragma warning disable 169");
    }
}  