using System;
using System.Linq;
using System.Runtime.CompilerServices;
using Microsoft.CodeAnalysis;
using Surject.Generators.Models.Collections;
using Surject.Generators.Models.Primitives;

namespace Surject.Generators.Models.Factories;

internal sealed class TypeReferenceModelFactory {
    private sealed record TypeReferenceModel : ITypeReferenceModel {
        internal TypeReferenceModel(TypeReferenceModelFactory factory, ITypeSymbol symbol) {
            factory._cache.Add(symbol, this);

            FQNGenericOmitted = symbol.GetFQNWithGenericsOmitted();
            FQNGenericBased = symbol.GetGenericDefinitionFQN();
            FQNArityBased = symbol.GetGenericArityFQN();
            FQNConstructedArgBased = symbol.GetConstructedTypeFQN();
            FlattenedNameNonArityBased = symbol.GetFlattenedConstructedName();
            Namespace = symbol.ContainingNamespace?.IsGlobalNamespace == false ? symbol.ContainingNamespace.ToDisplayString() : null;

            IsBasedOnTypeParameter = symbol.TypeKind == TypeKind.TypeParameter;

            if (symbol is INamedTypeSymbol namedTypeSymbol) {
                IsGeneric = namedTypeSymbol.IsGenericType;
                IsOpenGeneric = namedTypeSymbol.IsOpenGeneric();
                Constraints = namedTypeSymbol.GetTypeParamConstraints();

                if (IsGeneric && !IsBasedOnTypeParameter) {
                    UnboundGenericTypeRef = factory.CreateOrGetTypeReferenceModel(namedTypeSymbol.ConstructUnboundGenericType());
                    // TODO: Capture alloc
                    TypeArguments = [
                        .. namedTypeSymbol.TypeArguments.Select(typeSymbol =>
                            factory.CreateOrGetTypeReferenceModel(typeSymbol))
                    ];
                    TypeParameters = [
                        .. namedTypeSymbol.TypeParameters.Select(typeParameterSymbol =>
                            factory.CreateOrGetTypeReferenceModel(typeParameterSymbol))
                    ];
                }
                else {
                    TypeArguments = [];
                    TypeParameters = [];
                    UnboundGenericTypeRef = null;
                }

                BaseType = namedTypeSymbol.BaseType != null
                    ? factory.CreateOrGetTypeReferenceModel(namedTypeSymbol.BaseType)
                    : null;
                Interfaces = [
                    .. namedTypeSymbol.Interfaces.Select(interfaceSymbol =>
                        factory.CreateOrGetTypeReferenceModel(interfaceSymbol))
                ];
            }

            IsTrueValueType = symbol.IsValueType;
            TypeKind = symbol.TypeKind;
            SpecialType = symbol.SpecialType;
            
            _underlyingTypeSymbol = new WeakReference<ITypeSymbol>(symbol, false);
        }

        // need custom hash impl so we don't get stack overflow with circular type defs. 
        public override int GetHashCode() {
            unchecked {
                int hashCode = 17;
                hashCode = hashCode * (int)0xA5555529 + FQNGenericBased.GetHashCode() + TypeArguments.Length.GetHashCode();
                return hashCode;
            }
        }
        
        // TODO: Confirm that there is no autogenerated Equals() impl that includes the `UnderlyingTypeSymbol` in equality.
        // Inspect generation.
        
        // sadly this has to be done because I want to exclude the 'INamedTypeSymbol' member
        public bool Equals(ITypeReferenceModel? other) {
            return other is not null
                   && FQNGenericOmitted == other.FQNGenericOmitted
                   && FQNGenericBased == other.FQNGenericBased
                   && TypeArguments.Length == other.TypeArguments.Length
                   && FQNArityBased == other.FQNArityBased
                   && FQNConstructedArgBased == other.FQNConstructedArgBased
                   && FlattenedNameNonArityBased == other.FlattenedNameNonArityBased
                   && IsBasedOnTypeParameter == other.IsBasedOnTypeParameter
                   && IsGeneric == other.IsGeneric
                   && IsOpenGeneric == other.IsOpenGeneric
                   && IsTrueValueType == other.IsTrueValueType
                   && TypeKind == other.TypeKind
                   && SpecialType == other.SpecialType;
        }
        
        // The generated ToString() was messing up the debugger (recursive calls?), so we can just null it.
        // It is not needed anyway.
        // TODO: Look into this.
        public override string ToString() => "";

        public string FQNGenericOmitted { get; init; }
        public string FQNGenericBased { get; init; }
        public string FQNArityBased { get; init; }
        public string FQNConstructedArgBased { get; init; }
        public string FlattenedNameNonArityBased { get; init; }
        public string? Namespace { get; init; } // excluding 'global' 

        public bool IsBasedOnTypeParameter { get; init; }
        public bool IsGeneric { get; init; }
        public bool IsOpenGeneric { get; init; }
        public ITypeReferenceModel? UnboundGenericTypeRef { get; init; }
        public EquatableArray<ITypeReferenceModel> TypeArguments { get; init; }
        public EquatableArray<ITypeReferenceModel> TypeParameters { get; init; }
        public EquatableArray<ConstraintsModel> Constraints { get; init; }

        public bool IsTrueValueType { get; init; }
        public TypeKind TypeKind { get; init; }
        public SpecialType SpecialType { get; init; }

        public ITypeReferenceModel? BaseType { get; init; }
        public EquatableArray<ITypeReferenceModel> Interfaces { get; init; }
        
        private readonly WeakReference<ITypeSymbol> _underlyingTypeSymbol;
        public ITypeSymbol UnderlyingTypeSymbol => _underlyingTypeSymbol.GetTargetOrThrow();
    }

    // TODO: Check this. Because we are not using 'SymbolEqualityComparer.Default' we could be getting duplicate creations.
    private readonly ConditionalWeakTable<ITypeSymbol, ITypeReferenceModel> _cache = new();

    internal ITypeReferenceModel CreateOrGetTypeReferenceModel(ITypeSymbol typeSymbol) {
        if (_cache.TryGetValue(typeSymbol, out var cached)) {
            return cached;
        }

        ITypeReferenceModel @new = new TypeReferenceModel(this, typeSymbol);
        return @new;
    }
}