//HintName: Consumer_Injection.g.cs
// <auto-generated />
//------------------------------------------------------------------------------
// This code was automatically generated by Surject Generators.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//------------------------------------------------------------------------------

#pragma warning disable 169

namespace TestApp {
    [global::System.CodeDom.Compiler.GeneratedCode("SurjectGenerator", "1.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial    class Consumer : global::Surject.Abstractions.Lifecycle.IInjectable  {
        [global::System.ComponentModel.EditorBrowsable(
            global::System.ComponentModel.EditorBrowsableState.Never)]
        public void __Surject_Inject(global::Surject.Abstractions.Resolutions.IResolver resolver) {
            this.Init(
                resolver.Resolve<global::TestApp.Foo, global::Surject.Abstractions.Resolutions.NoneKey>(
                    new global::Surject.Abstractions.Resolutions.ResolveContext<global::Surject.Abstractions.Resolutions.NoneKey> { }
                ),
                resolver.Resolve<global::TestApp.Bar, global::Surject.Abstractions.Resolutions.NoneKey>(
                    new global::Surject.Abstractions.Resolutions.ResolveContext<global::Surject.Abstractions.Resolutions.NoneKey> { }
                )
            );
        }
    }
}
