using System.CodeDom.Compiler;
using System.Linq;
using Microsoft.CodeAnalysis;
using Surject.Generators.Models.Primitives;
using Surject.Shared.Helpers;

namespace Surject.Generators.Emitters;

internal static class EmitHelpers {
    internal static void EmitGeneratedFileHeader(IndentedTextWriter writer) {
        writer.WriteLine("// <auto-generated />");
        writer.WriteLine("//------------------------------------------------------------------------------");
        writer.WriteLine("// This code was automatically generated by Surject Generators.");
        writer.WriteLine("//");
        writer.WriteLine("// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.");
        writer.WriteLine("//------------------------------------------------------------------------------");
        writer.WriteLine();
        
        // Field declared but never used
        writer.WriteLine($"#pragma warning disable 169");
    }

    internal static void EmitGeneratedClassAttributes(IndentedTextWriter writer) {
        writer.WriteLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"SurjectGenerator\", \"1.0.0\")]");
        writer.WriteLine($"[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
    }
    
    internal static void EmitAggressiveInliningAttribute(IndentedTextWriter writer) {
        writer.WriteLine("[global::System.Runtime.CompilerServices.MethodImpl(");
        writer.Indent++;
        writer.WriteLine($"global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        writer.Indent--;
    }

    internal static void EmitNoInliningAttribute(IndentedTextWriter writer) {
        writer.WriteLine("[global::System.Runtime.CompilerServices.MethodImpl(");
        writer.Indent++;
        writer.WriteLine($"global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]");
        writer.Indent--;   
    }
    
    internal static void EmitEditorBrowsableNeverAttribute(IndentedTextWriter writer) {
        writer.WriteLine($"[global::System.ComponentModel.EditorBrowsable(");
        writer.Indent++;
        writer.WriteLine($"global::System.ComponentModel.EditorBrowsableState.Never)]");
        writer.Indent--;
    }

    internal static void EmitPreserveAttribute(IndentedTextWriter writer) {
        writer.WriteLine("[global::UnityEngine.Scripting.Preserve]");
    }

    internal static void EmitDefaultExecutionOrderAttribute(string value, IndentedTextWriter writer) {
        writer.WriteLine($"[global::UnityEngine.DefaultExecutionOrder(");
        writer.Indent++;
        writer.WriteLine($"{value})]");
        writer.Indent--;
    }

    internal static void EmitClassDeclarationFromModel(
        TypeDeclModel decl,
        IndentedTextWriter writer,
        string[]? inheritance = null)
    {
        ITypeReferenceModel typeRef = decl.AsTypeRef;
        
        string accessibility = decl.AccessModifier.AsDeclString();
        string isPartial = decl.IsPartial ? "partial " : string.Empty;
        string isSealed = decl.IsSealed && typeRef.TypeKind is not TypeKind.Struct ? "sealed " : string.Empty;
        string isStatic = decl.IsStatic ? "static " : string.Empty;
        
        string typeKeyword = typeRef.TypeKind switch {
            TypeKind.Interface => "interface",
            TypeKind.Struct => typeRef.IsRecord ? "record struct" : "struct",
            TypeKind.Enum => "enum",
            TypeKind.Class => typeRef.IsRecord ? "record" : "class",
            _ => ThrowHelpers.ThrowUnhandledBranch<string>(typeRef.TypeKind)
        };
        
        string typeParams = decl.AsTypeRef.TypeParameters.Length > 0
            ? "<" + string.Join(", ", decl.AsTypeRef.TypeParameters.Select(static tp => tp.FQNGenericBased)) + ">"
            : string.Empty;

        string constraints = decl.AsTypeRef.Constraints.Length > 0
            ? string.Join(" ", decl.AsTypeRef.Constraints.Select(static ct => ct.ToString()))
            : string.Empty;
        
        string inheritFrom = inheritance != null
            ? string.Join(", ", inheritance)
            : string.Empty;
        
        writer.WriteLine(
            $"{accessibility} {isPartial} {isSealed} {isStatic} {typeKeyword} " +
            $"{decl.TypeNameNoArityNoFQN}{typeParams} " +
            $"{(!string.IsNullOrEmpty(inheritFrom) ? $": {inheritFrom} " : "")}" +
            $"{constraints} {{"
        );
        
        writer.Indent++;
    }
}