using System.CodeDom.Compiler;
using System.Linq;
using Surject.Generators.Models.Primitives;

namespace Surject.Generators.Emitters;

internal static class EmitHelpers {
    internal static void EmitGeneratedFileHeader(IndentedTextWriter writer) {
        writer.WriteLine("// <auto-generated />");
        writer.WriteLine("//------------------------------------------------------------------------------");
        writer.WriteLine("// This code was automatically generated by Surject Generators.");
        writer.WriteLine("//");
        writer.WriteLine("// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.");
        writer.WriteLine("//------------------------------------------------------------------------------");
        writer.WriteLine();
        
        // Field declared but never used
        writer.WriteLine($"#pragma warning disable 169");
    }

    internal static void EmitGeneratedClassAttributes(IndentedTextWriter writer) {
        writer.WriteLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"SurjectGenerator\", \"1.0.0\")]");
        writer.WriteLine($"[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
    }
    
    internal static void EmitAggressiveInliningAttribute(IndentedTextWriter writer) {
        writer.WriteLine("[global::System.Runtime.CompilerServices.MethodImpl(");
        writer.Indent++;
        writer.WriteLine($"global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        writer.Indent--;
    }

    internal static void EmitNoInliningAttribute(IndentedTextWriter writer) {
        writer.WriteLine("[global::System.Runtime.CompilerServices.MethodImpl(");
        writer.Indent++;
        writer.WriteLine($"global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]");
        writer.Indent--;   
    }
    
    internal static void EmitEditorBrowsableNeverAttribute(IndentedTextWriter writer) {
        writer.WriteLine($"[global::System.ComponentModel.EditorBrowsable(");
        writer.Indent++;
        writer.WriteLine($"global::System.ComponentModel.EditorBrowsableState.Never)]");
        writer.Indent--;
    }

    internal static void EmitPreserveAttribute(IndentedTextWriter writer) {
        writer.WriteLine("[global::UnityEngine.Scripting.Preserve]");
    }

    internal static void EmitClassDeclarationFromModel(ClassDeclModel decl, IndentedTextWriter writer) {
        string accessibility = decl.AccessModifier.AsDeclString();
        string isPartial = decl.IsPartial ? "partial " : string.Empty;
        string isSealed = decl.IsSealed ? "sealed " : string.Empty;
        string isStatic = decl.IsStatic ? "static " : string.Empty;
        
        string typeParams = decl.ClassAsTypeRef.TypeParameters.Length > 0
            ? "<" + string.Join(", ", decl.ClassAsTypeRef.TypeParameters.Select(static tp => tp.FQNGenericBased)) + ">"
            : string.Empty;

        string constraints = decl.ClassAsTypeRef.Constraints.Length > 0
            ? string.Join(" ", decl.ClassAsTypeRef.Constraints.Select(static ct => ct.ToString()))
            : string.Empty;
        
        writer.WriteLine(
            $"{accessibility} {isPartial} {isSealed} {isStatic} class " +
            $"{decl.FQNNoGlobal}{typeParams} " +
            $"{constraints} {{"
        );
        
        writer.Indent++;
    }
}