using System.CodeDom.Compiler;

namespace Surject.Generators.Emitters;

internal static class EmitHelpers {
    internal static void EmitGeneratedFileHeader(IndentedTextWriter writer) {
        writer.WriteLine("// <auto-generated />");
        writer.WriteLine("//------------------------------------------------------------------------------");
        writer.WriteLine("// This code was automatically generated by Surject Generators.");
        writer.WriteLine("//");
        writer.WriteLine("// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.");
        writer.WriteLine("//------------------------------------------------------------------------------");
        writer.WriteLine();
        
        // Field declared but never used
        writer.WriteLine($"#pragma warning disable 169");
    }

    internal static void EmitGeneratedClassAttributes(IndentedTextWriter writer) {
        writer.WriteLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"SurjectGenerator\", \"1.0.0\")]");
        writer.WriteLine($"[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
    }
    
    internal static void EmitAggressiveInliningAttribute(IndentedTextWriter writer) {
        writer.WriteLine("[global::System.Runtime.CompilerServices.MethodImpl(");
        writer.Indent++;
        writer.WriteLine($"global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        writer.Indent--;
    }

    internal static void EmitNoInliningAttribute(IndentedTextWriter writer) {
        writer.WriteLine("[global::System.Runtime.CompilerServices.MethodImpl(");
        writer.Indent++;
        writer.WriteLine($"global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]");
        writer.Indent--;   
    }
    
    internal static void EmitEditorBrowsableNeverAttribute(IndentedTextWriter writer) {
        writer.WriteLine($"[global::System.ComponentModel.EditorBrowsable(");
        writer.Indent++;
        writer.WriteLine($"global::System.ComponentModel.EditorBrowsableState.Never)]");
        writer.Indent--;
    }   
}