name: Unit Tests (Debug)

on:
  push:
    branches: [dev]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - name: Restore
        run: dotnet restore

      - name: Build (Debug)
        run: dotnet build --configuration Debug --no-restore --property:PreserveDependenciesForRuntime=true

      - name: Test (Debug)
        run: dotnet test --configuration Debug --no-build --property:PreserveDependenciesForRuntime=true